---
- name: Calculate load index (CPU + RAM usage)
  set_fact:
    load_index: "{{ (ansible_processor_vcpus * ansible_processor_cores) | float / (ansible_memfree_mb | float + 1) | round(2) }}"

- name: Debug load metrics
  debug:
    msg: "Host={{ inventory_hostname }} | Load Index={{ load_index }}"

- name: Determine the most loaded host
  delegate_to: localhost
  run_once: true
  set_fact:
    most_loaded_host: "{{ hostvars | dict2items | selectattr('value.load_index', 'defined') | sort(attribute='value.load_index', reverse=true) | first }}"

- name: Save the most loaded host
  delegate_to: localhost
  run_once: true
  copy:
    content: "{{ most_loaded_host.key }}"
    dest: /tmp/most_loaded_host.txt
