---
- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present

- name: Configure NAT (iptables)
  iptables:
    chain: POSTROUTING
    table: nat
    jump: MASQUERADE
    out_interface: eth0
    protocol: all

- name: Save iptables rules
  command: iptables-save > /etc/iptables.rules
  changed_when: false

- name: Install persistent iptables
  apt:
    name: iptables-persistent
    state: present
  when: ansible_os_family == "Debian"
