- name: Add MongoDB repository (RHEL)
  yum_repository:
    name: mongodb-org-{{ mongodb.version }}
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/redhat/{{ ansible_distribution_major_version }}/mongodb-org/{{ mongodb.version }}/x86_64/
    gpgcheck: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-{{ mongodb.version }}.asc

- name: Install MongoDB packages (RHEL)
  yum:
    name: "{{ mongodb_packages }}"
    state: present
