- name: Detect OS and setup facts
  hosts: all_servers
  gather_facts: yes
  roles:
    - role: detect_os
  tags: [os, always]

- name: Discover server loads
  hosts: all_servers
  roles:
    - role: discover_load
  tags: [discover, load]

- name: what the vars
  hosts: localhost
  tasks:
    - name: check vars.
      set_fact:
      loaded_facts: "{{ lookup('file', '/tmp/ansible_facts.yml') } from_yan1 }}"

- name: show_var
  hosts: localhost
  tasks:
    - name: show me
      debug:
      msg: "{{ loaded_facts.least_loaded_host }}"
  tags: [show_var]

- name: Install MongoDB on least loaded server
  hosts: "{{ loaded_facts.least_loaded_host }}"
  roles:
    - role: mongo_install
    - role: firewall
  tags: [mongo, mongod]

- name: Configure router on most loaded server
  hosts: "{{ loaded_facts.most_loaded_host }}"
  roles:
    - role: routing_setup
  tags: [routing]

- name: Configure access control
  hosts: localhost
  roles:
    - role: dns
  tags: [access, hosts]
