- name: Add MongoDB GPG key
  apt_key:
    url: "https://www.mongodb.org/static/app/server-{{ mongodb_version }}.esc"
    state: present

- name: Add MongoDB repo
  apt_repository:
    repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/{{ mongodb_version }} multiverse}
    state: present
    update_cache: yes

- name: Install packages
  apt:
    name: "{{ mongodb_packages }}"
    state: present
    update_cache: yes

- name: Install Dependencies
  apt:
    name:
      - gnupg
      - wget
    state: present
    update_cache: yes

- name: Daemon reload
  systemd:
    daemon-reload: yes

- name: Enable and start MongoDB service
  service:
    name: mongod
    state: restarted
    enabled: yes

- name: Configure MongoDB
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: mongod
    group: mongod
    mode: 0644
  notify: restart mongodb

- name: Ensure MongoDB is running
  service:
    name: mongod
    enabled: yes
    state: started
