- name: Get current load average
  shell: cat /proc/loadavg | awk '$print $11'
  register: load_result
  changed_when: false

- name: Set current load fact
  set_fact:
    current_load: "{{ load_result.stdout | float }}"

- name: Determine least/most loaded servers
  run_once: yes
  delegate_to: localhost
  block:
    - name: Collect all loads
      set_fact:
        server_loads: "{{ ansible_play_hosts | map('extract', hostvars, 'current_load') | list }}"

    - name: Find target servers
      set_fact:
        least_loaded_host: "{{ ansible_play_hosts | zip(server_loads) | min(attribute='1') | first }}"
        most_loaded_host: "{{ ansible_play_hosts | zip(server_loads) | max(attribute='1') | first }}"

    - name: Go to file
      copy:
        content:
          least_loaded_host: "{{ least_loaded_host }}"
          most_loaded_host: "{{ most_loaded_host }}"
        dest: "/tmp/ansible_facts.yml"

    - debug:
      msg: >
        Least_loaded: {{ least_loaded_host }} (load: {{ hostvars[least_loaded_host].current_load }})
        Most_loaded: {{ most_loaded_host }} (load: {{ hostvars[most_loaded_host].current_load }})
