---
- name: Add MongoDB host entry
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  notify: flush dns cache

- name: Configure access control on MongoDB server
  block:
    - name: Wait for MongoDB to start
      wait_for:
        port: "{{ app_port }}"
        delay: 10
        timeout: 60

    - name: Create admin user
      community.mongodb.mongodb_user:
        login_host: "{{ ansible_host }}"
        login_port: "{{ app_port }}"
        login_user: admin
        login_password: admin
        database: admin
        username: admin
        password: admin
        roles: root
        state: present

    - name: Create application user
      community.mongodb.mongodb_user:
        login_host: "{{ ansible_host }}"
        login_port: "{{ app_port }}"
        login_user: admin
        login_password: admin
        database: myapp
        username: appuser
        password: apppassword
        roles: readWrite
        state: present
  when: inventory_hostname == mongodb_server|default('')
