---
- name: Allow MongoDB access only from the designated server
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 27017
    source: "{{ hostvars['redos']['ansible_default_ipv4']['address'] }}"
    jump: ACCEPT
    comment: "Allow MongoDB access only from redos"

- name: Block MongoDB for others
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 27017
    jump: DROP
    comment: "Block MongoDB for others"

- name: Save iptables rules
  command: iptables-save > /etc/iptables.rules
