- name: Install iptables
  apt:
    name: iptables
    state: present
    force_apt_get: yes

- name: Config MAT
  iptables:
    chain: POSTROUTING
    table: nat
    jump: MASQUERADE
    source: 192.168.0.0/24

- name: Save forwarding
  sysctl:
    name: "net.ipv4.ip_forward"
    value: "i"
    state: present
    reload: yes

- name: save config
  command: sysctl -p

- name: Save iptables rules
  become: yes
  shell: iptables-save > /etc/sysconfig/iptables
  args:
    executable: /bin/bash
