- name: restart networking
  service:
    name: network
    state: restarted
  when: ansible_os_family == "RedHat"

- name: restart networking
  service:
    name: networking
    state: restarted
  when: ansible_os_family == "Debian"
