---
- name: Analyze server load
  hosts: linux_servers
  roles:
    - load_analyzer

- name: Configure gateway
  hosts: "{{ lookup('file', '/tmp/most_loaded_host.txt') }}"
  roles:
    - gateway

- name: Deploy MongoDB
  hosts: mongodb_servers
  roles:
    - mongodb

- name: Configure firewall rules
  hosts: other_servers
  roles:
    - firewall

- name: Update DNS records
  hosts: all
  roles:
    - dns
